language: java

jdk:
  - oraclejdk8

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1b43537b-8817-4367-b41f-086cf01fb510

  email:
    - panyuyuyu@outlook.com