language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1b43537b-8817-4367-b41f-086cf01fb510


notifications:
  email:
    recipients:
      - panyuyuyu@outlook.com
